# Generated by Django 3.1.2 on 2020-10-14 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now=True)),
                ('author', models.CharField(max_length=50)),
                ('series', models.CharField(default='Нет', max_length=50)),
                ('brief_description', models.TextField()),
                ('language', models.CharField(max_length=15)),
                ('release_year', models.DateField()),
                ('picture', models.ImageField(upload_to='Images')),
                ('files', models.FileField(upload_to='Files')),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.book'),
        ),
        migrations.DeleteModel(
            name='library',
        ),
    ]
