# Generated by Django 3.1.1 on 2020-10-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20201014_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='files',
            field=models.FileField(upload_to='static\\Files'),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(upload_to='static\\Images'),
        ),
    ]
